<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>FlaUiNative</AssemblyName>
    <RootNamespace>FlaUiNative</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS0618</NoWarn>
  </PropertyGroup>

  <Target Name="CopyToFlaUILibraryBin" AfterTargets="Build">
    <Copy SourceFiles="$(TargetPath)"
          DestinationFiles="$(MSBuildThisFileDirectory)..\src\FlaUILibrary\bin\FlaUiNative.dll"
          SkipUnchangedFiles="true" />
  </Target>
</Project>
